apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: postgres
spec:
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: postgres
    spec:
      containers:
      - name: postgres
        image: postgres
        env:
          - name: POSTGRES_PASSWORD
            value: sonamwangyal
          - name: PGDATA
            value: /var/lib/postgresql/data/pgdata
          - name: POSTGRES_DB
            value: userdb
          - name: POSTGRES_INITDB_XLOGDIR
            value: /var/lib/postgresl/data/pgdata/transactionlog
        ports:
        - containerPort: 5432
        volumeMounts:
        - mountPath: /var/lib/postgresql/data
          name: postgresql-persistent-storage
  volumes:
    - name: postgresql-persistent-storage
      persistentVolumeClaim:
        claimName: postgres-pv-claim
