apiVersion: v1
kind: Service
metadata:
  name: postgres
  labels:
    name: postgres
spec:
  ports:
    - port: 5432
  selector:
    name: postgres
---
apiVersion: apps/v1beta1
kind: StatefulSet
metadata:
  name: postgres
spec:
  serviceName: postgres
  replicas: 1
  template:
    metadata:
      labels:
        app: postgres
    spec:
      containers:
      - name: postgres
        image: postgres
        env:
          - name: POSTGRES_PASSWORD
            value: sonamwangyal
          - name: PGDATA
            value: /var/lib/postgresql/data/pgdata
          - name: POSTGRES_DB
            value: userdb
        ports:
          - containerPort: 5432
        volumeMounts:
          - mountPath: /var/lib/postgresql/data
            name: pvclaim
#      initContainers:
#      - name: install
#        image: busybox
#        command: ['sh', '-c', 'set -ex;  echo "ordinal";']                 
#  volumes:
#  volumes:
#    - name: pg-data
#      persistentVolumeClaim:
#        claimName: postgres-pv-claim

  volumeClaimTemplates:
  - metadata:
     name: pvclaim
    spec:
      accessModes: [ "ReadWriteOnce" ]
      resources:
        requests:
          storage: 5Gi
