apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: postgres-pv-claim
  annotations:
    volume.beta.kubernetes.io/storage-class: rook-block
  labels:
    app: postgresql
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
