apiVersion: v1
kind: Service
metadata:
  name: postgres
  labels:
    name: postgres
spec:
  ports:
    - port: 5432
  selector:
    name: postgres
---
apiVersion: apps/v1beta1
kind: StatefulSet
metadata:
  name: postgres
spec:
  serviceName: postgres
  replicas: 1
  template:
    metadata:
      labels:
        app: postgres
    spec:
      containers:
      - name: postgres
        image: postgres
        env:
          - name: POSTGRES_PASSWORD
            value: sonamwangyal
          - name: PGDATA
            value: /var/lib/postgresql/data/pgdata
          - name: POSTGRES_DB
            value: userdb
        ports:
          - containerPort: 5432
        volumeMounts:
          - mountPath: /var/lib/postgresql/data
            name: pvclaim
        volumeMounts:
          - mountPath: /docker-entrypoint-initdb.d
            name: init-volume
      volumes:
      - name: init-volume
        emptyDir: {}
      initContainers:
      - name: install
        image: postgres
        command: ["bash", "-c", "set -ex;  echo 'ordinal' > 
         '/init-volume/hello.sonam'\n
         # Generate mysql server-id from pod ordinal index.\n
         [[ `hostname` =~ -([0-9]+)$ ]] || exit 1\n
         ordinal=${BASH_REMATCH[1]}\n
         echo server-id=$((100 + $ordinal)) > 'init-volume/server-id.txt'\n
         if [[ $ordinal -eq 0 ]]; then\n
           echo 'master server' > '/init-volume/server-name.txt'\n
         else\n
           cp 'worker server' > '/init-volume/server-name.txt'\n
         fi\n  
         "]
        volumeMounts:
        - name: init-volume
          mountPath: "/init-volume"                
  volumeClaimTemplates:
  - metadata:
     name: pvclaim
    spec:
      accessModes: [ "ReadWriteOnce" ]
      resources:
        requests:
          storage: 5Gi
